# Jekyll configuration for GitHub Pages
title: "Turtifications Documentation"
description: "A powerful Discord notification system built with Flask"
url: "https://yourusername.github.io"  # Replace 'yourusername' with your actual GitHub username
baseurl: "/repository-name"  # Replace 'repository-name' with your actual repository name

# GitHub Pages settings
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# Navigation
nav_sort: case_insensitive

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Collections
collections:
  guides:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"

# Footer content
footer_content: "Copyright &copy; 2024 Turtifications. Distributed under the MIT License."

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/yourusername/repository-name"  # Replace with your actual GitHub repository URL

# Footer last modified date
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/yourusername/repository-name"  # Replace with your actual GitHub repository URL
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"